# Generated by Django 4.1.7 on 2023-03-01 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("description", models.TextField()),
                ("time_create", models.DateTimeField(auto_now_add=True)),
                ("time_close", models.DateTimeField()),
                ("is_done", models.BooleanField(default=False)),
            ],
        ),
    ]
