# Generated by Django 4.1.7 on 2023-03-03 17:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("shop", "0002_task_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="owner",
            field=models.ManyToManyField(
                db_table="owner", related_name="owners", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
