# Generated by Django 4.1.7 on 2023-03-07 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0003_alter_task_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="time_close",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
